site_name: LinuxPi.ca
site_url: http://www.linuxpi.ca

theme:
  name: material
  copyright: © 2026 NolandTech
  logo: assets/images/favicon.png
  favicon: assets/favicon.ico
  # icon:
  #   logo: fontawesome/solid/jedi
  font:
    text: Roboto
    code: Roboto Mono
  palette:
    # Dark Mode
    - scheme: slate  # Enable dark mode
      toggle:
        icon: material/weather-sunny
        name: Dark mode
      primary: green
      accent: deep purple
    # Light Mode
    - scheme: default  # Enable light mode
      toggle:
        icon: material/weather-night
        name: Light mode
      primary: blue
      accent: deep orange
  features:
    - content.code.copy
    - content.code.select
    
nav:
  - Home: index.md
  - Linux Basics:
    - Introduction: linux-basics/intro.md
    - File Permissions: linux-basics/file-permissions.md
  - Advanced Pi Setup:
    - Headless Boot: advanced/headless.md

markdown_extensions:
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.highlight:
      anchor_linenums: true
      line_spans: __span
      pygments_lang_class: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences:
      custom_fences:
        - name: mermaid
          class: mermaid
          format: !!python/name:pymdownx.superfences.fence_code_format
  - admonition
  - pymdownx.details
  - pymdownx.tasklist
  - pymdownx.tabbed:
      alternate_style: true
      slugify: !!python/object/apply:pymdownx.slugs.slugify
        kwds:
          case: lower
          
extra_javascript:
  - https://unpkg.com/mermaid/dist/mermaid.min.js
  - https://unpkg.com/mermaid/dist/mermaid.initialize.js       

plugins:
  - search
  - git-revision-date-localized:
      type: date
  - macros
  - minify

extra:
  domain_name: "LinuxPi.ca"
  server_ip: "192.168.0.xxx"